apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todoapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rameshjavali/todoapp-manifests.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: todoapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
